name: Salami Test Suite

on:
  push:
  pull_request:
    branches: [ dev, main ]

jobs:
  run_tests:
    name: Run regression tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm test
