name: Salami Test Suite

on:
  push:
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  run_tests:
    name: Run regression tests and check linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install node 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Run regression tests
      run: npm test
    - name: Check formatting (eslint)
      run: npm run check-format
