name: Salami Web Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy GH pages website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - name: Build and deploy to GH pages 
      run: cd web && npm run deploy
